CREATE TABLE order_product
(
    order_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id       BIGINT                                  NOT NULL,
    order_id         BIGINT                                  NOT NULL,
    quantity         INT,
    CONSTRAINT pk_order_product PRIMARY KEY (order_product_id)
);

ALTER TABLE order_product
    ADD CONSTRAINT FK_ORDER_PRODUCT_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (order_id);

ALTER TABLE order_product
    ADD CONSTRAINT FK_ORDER_PRODUCT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);